### ISSUE TITLE
strange websocket error

### ISSUE THREAD

**Issue by piotr-sikora-v** [forbole/big-dipper-2.0-cosmos#1045]
Sometimes I see error like below, but (almost) everything works normal on my blockexploerer... I see validators, transactions and blocks... Hasura working fine on `10.10.10.1:8080` 

```
error - uncaughtException: Error: WebSocket was closed before the connection was established
    at WebSocket.close (/home/bigdipper/big-dipper-2.0-cosmos/node_modules/ws/lib/websocket.js:285:14)
    at SubscriptionClient.close (/home/bigdipper/big-dipper-2.0-cosmos/node_modules/subscriptions-transport-ws/src/client.ts:173:19)
    at Timeout._onTimeout (/home/bigdipper/big-dipper-2.0-cosmos/node_modules/subscriptions-transport-ws/src/client.ts:551:14)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) {
  domainEmitter: WebSocket {
    _events: [Object: null prototype] {},
    _eventsCount: 0,
    _maxListeners: undefined,
    _binaryType: 'nodebuffer',
    _closeCode: 1006,
    _closeFrameReceived: false,
    _closeFrameSent: false,
    _closeMessage: <Buffer >,
    _closeTimer: null,
    _extensions: {},
    _paused: false,
    _protocol: '',
    _readyState: 2,
    _receiver: null,
    _sender: null,
    _socket: null,
    _bufferedAmount: 0,
    _isServer: false,
    _redirects: 0,
    _url: 'ws://10.10.10.1:8080/v1/graphql',
    _req: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: true,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: true,
      socket: [Socket],
      _header: 'GET /v1/graphql HTTP/1.1\r\n' +
        'Sec-WebSocket-Version: 13\r\n' +
        'Sec-WebSocket-Key: 5HMEbyg9PxlFT9qzNiJc0w==\r\n' +
        'Connection: Upgrade\r\n' +
        'Upgrade: websocket\r\n' +
        'Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits\r\n' +
        'Sec-WebSocket-Protocol: graphql-ws\r\n' +
        'Host: 10.10.10.1:8080\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: undefined,
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/v1/graphql',
      _ended: false,
      res: null,
      aborted: true,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: '10.10.10.1',
      protocol: 'http:',
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kEndCalled)]: true,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(kUniqueHeaders)]: null,
      [Symbol(kAborted)]: true,
      [Symbol(kError)]: undefined
    },
    [Symbol(kCapture)]: false
  },
  domainThrown: false
}
```

**Comment by teamchong** [comment]
sorry for the late reply, I think upgrade from the deprecated `graphql-transport-ws` to `graphql-ws` seems to improve the situation.

**Comment by teamchong** [comment]
Hi there, I hope this message finds you well. I noticed that there has been no activity on this issue for a while now. If you have any further questions or updates, please let me know and I'd be happy to assist. I'll go ahead and close this issue to keep our GitHub repository organized. If you need to revisit this issue in the future, feel free to open a new one. Thank you for your understanding.
