### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by whonion** [forbole/big-dipper-2.0-cosmos#1055]
```
SyntaxError: Invalid URL:
    at initAsClient (/app/node_modules/ws/lib/websocket.js:673:13)
    at new WebSocket (/app/node_modules/ws/lib/websocket.js:85:7)
    at SubscriptionClient.connect (/app/node_modules/subscriptions-transport-ws/dist/client.js:446:23)
    at new SubscriptionClient (/app/node_modules/subscriptions-transport-ws/dist/client.js:99:18)
    at new WebSocketLink (/app/node_modules/@apollo/client/link/ws/ws.cjs:17:40)
    at 20539 (/app/.next/server/pages/_app.js:56:16)
    at __webpack_require__ (/app/.next/server/webpack-runtime.js:25:42)
    at /app/.next/server/pages/_app.js:509:77
    at __webpack_require__.a (/app/.next/server/webpack-runtime.js:89:13)
    at 6592 (/app/.next/server/pages/_app.js:495:21)
SyntaxError: Invalid URL:
    at initAsClient (/app/node_modules/ws/lib/websocket.js:673:13)
    at new WebSocket (/app/node_modules/ws/lib/websocket.js:85:7)
    at SubscriptionClient.connect (/app/node_modules/subscriptions-transport-ws/dist/client.js:446:23)
    at new SubscriptionClient (/app/node_modules/subscriptions-transport-ws/dist/client.js:99:18)
    at new WebSocketLink (/app/node_modules/@apollo/client/link/ws/ws.cjs:17:40)
    at 20539 (/app/.next/server/pages/_app.js:56:16)
    at __webpack_require__ (/app/.next/server/webpack-runtime.js:25:42)
    at /app/.next/server/pages/_app.js:509:77
    at __webpack_require__.a (/app/.next/server/webpack-runtime.js:89:13)
    at 6592 (/app/.next/server/pages/_app.js:495:21)

> Build error occurred
Error: Failed to collect page data for /accounts/[address]
    at /app/node_modules/next/dist/build/utils.js:916:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'Error'
}
The command '/bin/sh -c yarn install && yarn build' returned a non-zero code: 1
```

**Comment by whonion** [comment]
**I guess issue r is related to changing the package manager from npm to yarn**

**Comment by teamchong** [comment]
sorry for the late reply 
what's your `GRAPHQL_WS`  environment variable?
by default it is set to `ws://localhost:8080/v1/graphql`
do you have the Hasura server running on 8080 port?

**Comment by teamchong** [comment]
Hi there, I hope this message finds you well. I noticed that there has been no activity on this issue for a while now. If you have any further questions or updates, please let me know and I'd be happy to assist. I'll go ahead and close this issue to keep our GitHub repository organized. If you need to revisit this issue in the future, feel free to open a new one. Thank you for your understanding.

**Comment by whonion** [comment]
> Hi there, I hope this message finds you well. I noticed that there has been no activity on this issue for a while now. If you have any further questions or updates, please let me know and I'd be happy to assist. I'll go ahead and close this issue to keep our GitHub repository organized. If you need to revisit this issue in the future, feel free to open a new one. Thank you for your understanding.

I'm sorry, I completely forgot to answer.
Yes, I tried running locally, the problem was that Hasura was not running.
