### ISSUE TITLE
Getting the error when run "yarn run graphql:codegen"

### ISSUE THREAD

**Issue by AntonMashnin** [forbole/big-dipper-2.0-cosmos#1329]
Hello Team,

I'm getting the error when trying to run: "yarn run graphql:codegen"
`✔ Parse Configuration
⚠ Generate outputs
  ❯ Generate to ./src/graphql/types/general_types.ts
    ✔ Load GraphQL schemas
    ✔ Load GraphQL documents
    ✖ GraphQL Document Validation failed with 68 errors;
      Error 0: Cannot query field "action_validator_commission_amount" on type "query_root".
      at /home/explorer/big-dipper/big-dipper-2.0-cosmos/apps/web-crossfi/src/graphql/general/account_details_documents.ts:3:5
      Error 1: Cannot query field "action_delegator_withdraw_address" on type "query_root".
      at /home/explorer/big-dipper/big-dipper-2.0-cosmos/apps/web-crossfi/src/graphql/general/account_details_documents.ts:3:5
      Error 2: Cannot query field "action_account_balance" on type "query_root".
      at /home/explorer/big-dipper/big-dipper-2.0-cosmos/apps/web-crossfi/src/graphql/general/account_details_documents.ts:3:5
      Error 3: Cannot query field "action_delegation_total" on type "query_root".
      at /home/explorer/big-dipper/big-dipper-2.0-cosmos/apps/web-crossfi/src/graphql/general/account_details_documents.ts:3:5
      Error 4: Cannot query field "action_unbonding_delegation_total" on type "query_root".
      at /home/explorer/big-dipper/big-dipper-2.0-cosmos/apps/web-crossfi/src/graphql/general/account_details_documents.ts:3:5
      Error 5: Cannot query field "action_delegation_reward" on type "query_root".
      at /home/explorer/big-dipper/big-dipper-2.0-cosmos/apps/web-crossfi/src/graphql/general/account_details_documents.ts:3:5
      Error 6: Cannot query field "action_delegation" on type "query_root".
      at /home/explorer/big-dipper/big-dipper-2.0-cosmos/apps/web-crossfi/src/graphql/general/account_details_documents.ts:8:5
      Error 7: Cannot query field "action_redelegation" on type "query_root".
      at /home/explorer/big-dipper/big-dipper-2.0-cosmos/apps/web-crossfi/src/graphql/general/account_details_documents.ts:8:5
      Error 8: Cannot query field "action_unbonding_delegation" on type "query_root".
      at /home/explorer/big-dipper/big-dipper-2.0-cosmos/apps/web-crossfi/src/graphql/general/account_details_documents.ts:8:5
      Error 9: Cannot query field "validator_status_aggregate" on type "query_root".
      at /home/explorer/big-dipper/big-dipper-2.0-cosmos/apps/web-crossfi/src/graphql/general/active_validator_count.graphql:2:3
      Error 10: Cannot query field "validator_status_aggregate" on type "query_root".
      at /home/explorer/big-dipper/big-dipper-2.0-cosmos/apps/web-crossfi/src/graphql/general/active_validator_count.graphql:7:3
      Error 11: Cannot query field "validator_status_aggregate" on type "query_root".
      at /home/explorer/big-dipper/big-dipper-2.0-cosmos/apps/web-crossfi/src/graphql/general/active_validator_count.graphql:12:3
      Error 12: Unknown type "bigint". Did you mean "Int"?
      at /home/explorer/big-dipper/big-dipper-2.0-cosmos/apps/web-crossfi/src/graphql/general/block_details.graphql:1:29
      Error 13: Unknown type "bigint". Did you mean "Int"?
      at /home/explorer/big-dipper/big-dipper-2.0-cosmos/apps/web-crossfi/src/graphql/general/block_details.graphql:1:55
      Error 14: Cannot query field "transaction" on type "query_root".
      at /home/explorer/big-dipper/big-dipper-2.0-cosmos/apps/web-crossfi/src/graphql/general/block_details.graphql:2:3
      Error 15: Cannot query field "block" on type "query_root".
      at /home/explorer/big-dipper/big-dipper-2.0-cosmos/apps/web-crossfi/src/graphql/general/block_details.graphql:9:3
      Error 16: Cannot query field "pre_commit_aggregate" on type "query_root".
      at /home/explorer/big-dipper/big-dipper-2.0-cosmos/apps/web-crossfi/src/graphql/general/block_details.graphql:20:3
      Error 17: Cannot query field "pre_commit" on type "query_root".
      at /home/explorer/big-dipper/big-dipper-2.0-cosmos/apps/web-crossfi/src/graphql/general/block_details.graphql:27:3
      Error 18: Cannot query field "average_block_time_per_hour" on type "query_root".
      at /home/explorer/big-dipper/big-dipper-2.0-cosmos/apps/web-crossfi/src/graphql/general/block_time.graphql:2:3
      Error 19: Cannot query field "block" on type "query_root".
      at /home/explorer/big-dipper/big-dipper-2.0-cosmos/apps/web-crossfi/src/graphql/general/block_time.graphql:8:3
      Error 20: Cannot query field "block" on type "query_root".
      at /home/explorer/big-dipper/big-dipper-2.0-cosmos/apps/web-crossfi/src/graphql/general/blocks.graphql:17:3
      Error 21: Cannot query field "genesis" on type "query_root".
      at /home/explorer/big-dipper/big-dipper-2.0-cosmos/apps/web-crossfi/src/graphql/general/chain_id.graphql:2:3
      Error 22: Cannot query field "community_pool" on type "query_root".
      at /home/explorer/big-dipper/big-dipper-2.0-cosmos/apps/web-crossfi/src/graphql/general/market_data.graphql:2:3
      Error 23: Cannot query field "inflation" on type "query_root".
      at /home/explorer/big-dipper/big-dipper-2.0-cosmos/apps/web-crossfi/src/graphql/general/market_data.graphql:5:3
      Error 24: Cannot query field "token_price" on type "query_root".
      at /home/explorer/big-dipper/big-dipper-2.0-cosmos/apps/web-crossfi/src/graphql/general/market_data.graphql:8:3
      Error 25: Cannot query field "supply" on type "query_root".
      at /home/explorer/big-dipper/big-dipper-2.0-cosmos/apps/web-crossfi/src/graphql/general/market_data.graphql:12:3
      Error 26: Cannot query field "staking_pool" on type "query_root".
      at /home/explorer/big-dipper/big-dipper-2.0-cosmos/apps/web-crossfi/src/graphql/general/market_data.graphql:15:3
      Error 27: Cannot query field "distribution_params" on type "query_root".
      at /home/explorer/big-dipper/big-dipper-2.0-cosmos/apps/web-crossfi/src/graphql/general/market_data.graphql:18:3
      Error 28: Unknown type "_text".
      at /home/explorer/big-dipper/big-dipper-2.0-cosmos/apps/web-crossfi/src/graphql/general/messages_by_address.graphql:1:38
      Error 29: Unknown type "bigint". Did you mean "Int"?
      at /home/explorer/big-dipper/big-dipper-2.0-cosmos/apps/web-crossfi/src/graphql/general/messages_by_address.graphql:1:53
      Error 30: Unknown type "bigint". Did you mean "Int"?
      at /home/explorer/big-dipper/big-dipper-2.0-cosmos/apps/web-crossfi/src/graphql/general/messages_by_address.graphql:1:75
      Error 31: Unknown type "_text".
      at /home/explorer/big-dipper/big-dipper-2.0-cosmos/apps/web-crossfi/src/graphql/general/messages_by_address.graphql:1:94
      Error 32: Cannot query field "messages_by_address" on type "query_root".
      at /home/explorer/big-dipper/big-dipper-2.0-cosmos/apps/web-crossfi/src/graphql/general/messages_by_address.graphql:2:3
      Error 33: Cannot query field "validator_status_aggregate" on type "query_root".
      at /home/explorer/big-dipper/big-dipper-2.0-cosmos/apps/web-crossfi/src/graphql/general/online_voting_power.graphql:2:3
      Error 34: Cannot query field "validator_voting_power_aggregate" on type "query_root".
      at /home/explorer/big-dipper/big-dipper-2.0-cosmos/apps/web-crossfi/src/graphql/general/online_voting_power.graphql:7:3
      Error 35: Cannot query field "staking_pool" on type "query_root".
      at /home/explorer/big-dipper/big-dipper-2.0-cosmos/apps/web-crossfi/src/graphql/general/online_voting_power.graphql:14:3
      Error 36: Cannot query field "staking_params" on type "query_root".
      at /home/explorer/big-dipper/big-dipper-2.0-cosmos/apps/web-crossfi/src/graphql/general/online_voting_power.graphql:17:3
      Error 37: Cannot query field "staking_params" on type "query_root".
      at /home/explorer/big-dipper/big-dipper-2.0-cosmos/apps/web-crossfi/src/graphql/general/params.graphql:2:3
      Error 38: Cannot query field "slashing_params" on type "query_root".
      at /home/explorer/big-dipper/big-dipper-2.0-cosmos/apps/web-crossfi/src/graphql/general/params.graphql:5:3
      Error 39: Cannot query field "mint_params" on type "query_root".
      at /home/explorer/big-dipper/big-dipper-2.0-cosmos/apps/web-crossfi/src/graphql/general/params.graphql:8:3
      Error 40: Cannot query field "distribution_params" on type "query_root".
      at /home/explorer/big-dipper/big-dipper-2.0-cosmos/apps/web-crossfi/src/graphql/general/params.graphql:11:3
      Error 41: Cannot query field "gov_params" on type "query_root".
      at /home/explorer/big-dipper/big-dipper-2.0-cosmos/apps/web-crossfi/src/graphql/general/params.graphql:14:3
      Error 42: Cannot query field "proposal" on type "query_root".
      at /home/explorer/big-dipper/big-dipper-2.0-cosmos/apps/web-crossfi/src/graphql/general/proposal_details.graphql:2:3
      Error 43: Cannot query field "proposal_tally_result" on type "query_root".
      at /home/explorer/big-dipper/big-dipper-2.0-cosmos/apps/web-crossfi/src/graphql/general/proposal_details.graphql:18:2
      Error 44: Cannot query field "proposal_staking_pool_snapshot" on type "query_root".
      at /home/explorer/big-dipper/big-dipper-2.0-cosmos/apps/web-crossfi/src/graphql/general/proposal_details.graphql:24:3
      Error 45: Cannot query field "gov_params" on type "query_root".
      at /home/explorer/big-dipper/big-dipper-2.0-cosmos/apps/web-crossfi/src/graphql/general/proposal_details.graphql:27:3
      Error 46: Cannot query field "proposal_deposit" on type "query_root".
      at /home/explorer/big-dipper/big-dipper-2.0-cosmos/apps/web-crossfi/src/graphql/general/proposal_details.graphql:33:3
      Error 47: Cannot query field "proposal_vote" on type "query_root".
      at /home/explorer/big-dipper/big-dipper-2.0-cosmos/apps/web-crossfi/src/graphql/general/proposal_details.graphql:43:3
      Error 48: Cannot query field "proposal_validator_status_snapshot" on type "query_root".
      at /home/explorer/big-dipper/big-dipper-2.0-cosmos/apps/web-crossfi/src/graphql/general/proposal_details.graphql:47:3
      Error 49: Cannot query field "proposal" on type "query_root".
      at /home/explorer/big-dipper/big-dipper-2.0-cosmos/apps/web-crossfi/src/graphql/general/proposals.graphql:2:3
      Error 50: Cannot query field "proposal_aggregate" on type "query_root".
      at /home/explorer/big-dipper/big-dipper-2.0-cosmos/apps/web-crossfi/src/graphql/general/proposals.graphql:8:3
      Error 51: Cannot query field "token_price_history" on type "query_root".
      at /home/explorer/big-dipper/big-dipper-2.0-cosmos/apps/web-crossfi/src/graphql/general/token_price.graphql:12:3
      Error 52: Cannot query field "staking_params" on type "query_root".
      at /home/explorer/big-dipper/big-dipper-2.0-cosmos/apps/web-crossfi/src/graphql/general/tokenomics.graphql:2:3
      Error 53: Cannot query field "staking_pool" on type "query_root".
      at /home/explorer/big-dipper/big-dipper-2.0-cosmos/apps/web-crossfi/src/graphql/general/tokenomics.graphql:5:3
      Error 54: Cannot query field "supply" on type "query_root".
      at /home/explorer/big-dipper/big-dipper-2.0-cosmos/apps/web-crossfi/src/graphql/general/tokenomics.graphql:9:3
      Error 55: Cannot query field "transaction" on type "query_root".
      at /home/explorer/big-dipper/big-dipper-2.0-cosmos/apps/web-crossfi/src/graphql/general/transaction_details.graphql:2:3
      Error 56: Cannot query field "transaction" on type "query_root".
      at /home/explorer/big-dipper/big-dipper-2.0-cosmos/apps/web-crossfi/src/graphql/general/transactions.graphql:15:3
      Error 57: Cannot query field "staking_pool" on type "query_root".
      at /home/explorer/big-dipper/big-dipper-2.0-cosmos/apps/web-crossfi/src/graphql/general/validator_details.graphql:27:3
      Error 58: Cannot query field "validator" on type "query_root".
      at /home/explorer/big-dipper/big-dipper-2.0-cosmos/apps/web-crossfi/src/graphql/general/validator_details.graphql:31:3
      Error 59: Cannot query field "slashing_params" on type "query_root".
      at /home/explorer/big-dipper/big-dipper-2.0-cosmos/apps/web-crossfi/src/graphql/general/validator_details.graphql:58:3
      Error 60: Cannot query field "action_validator_delegations" on type "query_root".
      at /home/explorer/big-dipper/big-dipper-2.0-cosmos/apps/web-crossfi/src/graphql/general/validator_details_documents.ts:8:5
      Error 61: Cannot query field "action_validator_redelegations_from" on type "query_root".
      at /home/explorer/big-dipper/big-dipper-2.0-cosmos/apps/web-crossfi/src/graphql/general/validator_details_documents.ts:8:5
      Error 62: Cannot query field "action_validator_unbonding_delegations" on type "query_root".
      at /home/explorer/big-dipper/big-dipper-2.0-cosmos/apps/web-crossfi/src/graphql/general/validator_details_documents.ts:8:5
      Error 63: Cannot query field "staking_pool" on type "query_root".
      at /home/explorer/big-dipper/big-dipper-2.0-cosmos/apps/web-crossfi/src/graphql/general/validators.graphql:2:3
      Error 64: Cannot query field "validator" on type "query_root".
      at /home/explorer/big-dipper/big-dipper-2.0-cosmos/apps/web-crossfi/src/graphql/general/validators.graphql:5:3
      Error 65: Cannot query field "slashing_params" on type "query_root".
      at /home/explorer/big-dipper/big-dipper-2.0-cosmos/apps/web-crossfi/src/graphql/general/validators.graphql:29:3
      Error 66: Cannot query field "validator" on type "query_root".
      at /home/explorer/big-dipper/big-dipper-2.0-cosmos/apps/web-crossfi/src/graphql/general/validators_address_list.graphql:2:3
      Error 67: Cannot query field "validator" on type "query_root".
      at /home/explorer/big-dipper/big-dipper-2.0-cosmos/apps/web-crossfi/src/graphql/general/validators_address_list.graphql:17:3
`

But when I checked "Hasura" all work fine: 
`$ curl http://localhost:3001/account_balance --data '{ "input": { "address": "mx1a0r52e3c6gf0039rdw72g3se2hhr9vmc9vhtcs"} }'
{"coins":[{"amount":"6900937235638175963","denom":"mpx"},{"amount":"1886329821648094639","denom":"xfi"}]}`

**Comment by nezha90** [comment]
I have the same problem.
Have you solved it?

**Comment by SherpaDAO** [comment]
Following
