### ISSUE TITLE
Trying to Build base_v1.8.4 resulting In Error

### ISSUE THREAD

**Issue by lightiv** [forbole/big-dipper-2.0-cosmos#622]
info  - Loaded env from /home/lightiv/big-dipper-2.0-cosmos/.env
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
Failed to compile.

./src/components/nav/components/seach_bar/hooks.tsx:39:49
Type error: Property 'profile' does not exist on type '{ desmosProfile: boolean; forboleX: boolean; }'.

  37 |         router.push(ACCOUNT_DETAILS(parsedValue));
  38 |       } else if (/^@/.test(parsedValue)) {
> 39 |         const configProfile = chainConfig.extra.profile;
     |                                                 ^
  40 |         if (!configProfile) {
  41 |           toast(t('common:profilesNotEnabled'));
  42 |         } else if (parsedValue === '@') {
info  - Checking validity of types .npm ERR! code ELIFECYCLE
npm ERR! errno 1

![image](https://user-images.githubusercontent.com/36428473/147696357-65417222-688d-46b4-ae88-fa490fa1f82b.png)

**Comment by lightiv** [comment]
This is happening with ```npm run build``` command

**Comment by lightiv** [comment]
Log file:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@6.14.4
3 info using node@v10.19.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle big-dipper-2.0-cosmos@1.0.0~prebuild: big-dipper-2.0-cosmos@1.0.0
6 info lifecycle big-dipper-2.0-cosmos@1.0.0~build: big-dipper-2.0-cosmos@1.0.0
7 verbose lifecycle big-dipper-2.0-cosmos@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle big-dipper-2.0-cosmos@1.0.0~build: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/lightiv/big-dipper-2.0-cosmos/node_modules/.bin:/home/lightiv/.evmosd/cosmovisor/current/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:~/bin:/home/lightiv/.local/bin:/home/lightiv/.hermes/bin:/usr/local/go:/home/lightiv/go::/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin:/home/lightiv/go/bin
9 verbose lifecycle big-dipper-2.0-cosmos@1.0.0~build: CWD: /home/lightiv/big-dipper-2.0-cosmos
10 silly lifecycle big-dipper-2.0-cosmos@1.0.0~build: Args: [ '-c', 'npm run build:next && npm run build:server' ]
11 silly lifecycle big-dipper-2.0-cosmos@1.0.0~build: Returned: code: 1  signal: null
12 info lifecycle big-dipper-2.0-cosmos@1.0.0~build: Failed to exec build script
13 verbose stack Error: big-dipper-2.0-cosmos@1.0.0 build: `npm run build:next && npm run build:server`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid big-dipper-2.0-cosmos@1.0.0
15 verbose cwd /home/lightiv/big-dipper-2.0-cosmos
16 verbose Linux 5.4.0-91-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
18 verbose node v10.19.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error big-dipper-2.0-cosmos@1.0.0 build: `npm run build:next && npm run build:server`
22 error Exit status 1
23 error Failed at the big-dipper-2.0-cosmos@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by ryuash** [comment]
Can't reproduce but I can tell your config file is very outdated as `forboleX` and `desmosProfile` is no longer being used. Here is an example of the config for this version:

```
{
  "title": "Desmos Block Explorer",
  "network": "desmos-mainnet-1",
  "icon": "https://raw.githubusercontent.com/forbole/big-dipper-assets/master/desmos/icon.svg?sanitize=true",
  "logo": {
    "default": "https://raw.githubusercontent.com/forbole/big-dipper-assets/master/desmos/logo.svg?sanitize=true"
  },
  "prefix": {
    "consensus": "desmosvalcons",
    "validator": "desmosvaloper",
    "account": "desmos"
  },
  "genesis": {
    "time": "2021-07-13T08:00:00",
    "height": 1
  },
  "primaryTokenUnit": "udsm",
  "tokenUnits": {
    "udsm": {
      "display": "dsm",
      "exponent": 6
    }
  },
  "extra": {
    "profile": true
  }
}
```
